name: Deploy Backend to Elastic Beanstalk
on:
    workflow_dispatch:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
            name: artifact
            path: |
              api/*
              !api/src
              !api/test
              !api/node_modules
  deploy-dev:
    name: Deploy DEV Environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
            name: artifact
            path: artifact
      - name: Zip Artifact for Deployment
        run: |
          cd artifact
          zip -r ../service.zip ./*
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: dev-api-rest-do-zero-a-aws-com-terraform
          environment_name: dev-api-rest-do-zero-a-aws-com-terraform
          region: us-east-1
          version_label: ${{ github.run_id }}
          deployment_package: service.zip
          use_existing_version_if_available: true